### Variáveis de ambiente (opcional)
@baseUrl = http://localhost:3000
@contentType = application/json

### POST /auth/signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "name": "Jonathan Gama",
  "email": "gama@hotmail.com",
  "password": "123456"
}

### POST /auth/signin
# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
  "name": "Jonathan Gama",
  "email": "gama@hotmail.com",
  "password": "123456"
}

### GET /auth/me
GET {{baseUrl}}/auth/me
Content-Type: {{contentType}}
Authorization: Bearer {{signin.response.body.accessToken}}


