### Variáveis de ambiente (opcional)
@baseUrl = http://localhost:3000
@contentType = application/json

### POST /auth/signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "name": "Jonathan Gama",
  "email": "test@hotmail.com",
  "password": "123465"
}

### POST /auth/signin
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
 "name": "Jonathan Gama",
  "email": "test@hotmail.com",
  "password": "123465"
}

### GET / (exemplo de requisição GET)
GET {{baseUrl}}/

